{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "df8e403e_aaa68d98",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1882601
      },
      "writtenOn": "2023-11-28T00:29:23Z",
      "side": 1,
      "message": "Fix was verified locally (see [this comment](https://b.corp.google.com/issues/313385486#comment2) on the bug).",
      "revId": "0372255af1939356846cd6d28044bcdc5ec7f6d6",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}