{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "004be0d6_7248c56a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1005970
      },
      "writtenOn": "2021-06-29T16:17:50Z",
      "side": 1,
      "message": "Verified that the test indeed runs and passes in spite of the exceptions. I will upload the logcat in buganizer.",
      "revId": "170e19e7e915e91ce5ccee352c773746774ca9c3",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}