{
  "comments": [
    {
      "key": {
        "uuid": "d43503b9_987ad952",
        "filename": "public/domain.te",
        "patchSetId": 2
      },
      "lineNbr": 638,
      "author": {
        "id": 1557662
      },
      "writtenOn": "2019-11-21T20:51:43Z",
      "side": 1,
      "message": "This came from test failure: \nlibsepol.report_failure: neverallow on line 632 of system/sepolicy/public/domain.te (or line 11993 of policy.conf) violated by allow permissioncontroller_app incidentcompanion_service:service_manager { find };",
      "revId": "4b3f7608ebacce3f7c91c3b1879d1647f9b48b98",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    }
  ]
}