{
  "comments": [
    {
      "key": {
        "uuid": "dadf3a04_31560e56",
        "filename": "/COMMIT_MSG",
        "patchSetId": 3
      },
      "lineNbr": 16,
      "author": {
        "id": 1124693
      },
      "writtenOn": "2019-01-25T18:35:14Z",
      "side": 1,
      "message": "oops, wrong bug number here, should be 119305624",
      "range": {
        "startLine": 16,
        "startChar": 5,
        "endLine": 16,
        "endChar": 12
      },
      "revId": "4eb68150aa0cf79dd375d80886aa59c693e5bcda",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    }
  ]
}