{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "b92071bd_6be65dc9",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 6
      },
      "lineNbr": 0,
      "author": {
        "id": 1954616
      },
      "writtenOn": "2024-02-21T19:49:00Z",
      "side": 1,
      "message": "The app data in storage areas now has the type `app_data_file`, so vold_prepare_subdirs has no access to it anymore.",
      "revId": "eddfe1abaf13f06f21a45a4e3fe5caacac5d17d2",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}